# Generated by Django 4.1.1 on 2022-09-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='sss@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
