# Generated by Django 4.1.1 on 2022-09-21 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_author_alter_recipe_liked'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cookt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='prept',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='totalt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
